services:
  mongo:
    image: mongo:latest
    container_name: taskflow-mongo
    ports:
      - "27017:27017"
    networks:
      - taskflow-network
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./taskflow-backend
    image: taskflow-backend
    container_name: taskflow-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - taskflow-network

  frontend:
    build:
      context: ./taskflow-frontend
    image: taskflow-frontend
    container_name: taskflow-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - taskflow-network

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: taskflow-jenkins
    container_name: taskflow-jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - taskflow-network
    restart: always

  sonarqube:
    image: sonarqube:community
    container_name: taskflow-sonarqube
    ports:
      - "9000:9000"
    networks:
      - taskflow-network
    restart: always

networks:
  taskflow-network:
    driver: bridge

volumes:
  jenkins_home:
  mongo_data: