sonar.projectKey=taskflow
sonar.projectName=Taskflow
sonar.projectVersion=1.0
sonar.sources=./taskflow-backend/src
sonar.exclusions=**/node_modules/**
sonar.host.url=http://taskflow-sonarqube:9000
sonar.login=<SONAR_TOKEN>